import ProfileMenu from '@/components/ui/ProfileMenu';

export const metadata = {
    title: "Página de More",
    description: "Generated by create next app",
  };

export default function Profile() {

    return (
        <div className="min-h-screen flex flex-col justify-center items-center bg-gray-100">
                <ProfileMenu /> {/* Seu componente real */}
        </div>
    );
}
