import RecipeCreateForm from '@/components/forms/RecipeCreateForm';
import { cookies } from 'next/headers';
import React from 'react';

export const metadata = {
  title: 'Página de Teste',
  description: 'Generated by create next app',
};

export default async function FoodList() {
  const cookieStore = cookies();
  const userInfoCookie = cookieStore.get('user_info')?.value;

  let userId = null;

  if (userInfoCookie) {
    try {
      const parsed = JSON.parse(userInfoCookie);
      userId = parsed._id;
    } catch (error) {
      console.error('Erro ao parsear cookie user_info:', error);
    }
  }

  return (
    <div className="flex flex-col justify-center items-center mt-20">
      {userId ? (
        <RecipeCreateForm userId={userId} />
      ) : (
        <p className="text-red-500">Usuário não autenticado.</p>
      )}
    </div>
  );
}
