import FormFoodSearch from '@/components/forms/FormFoodSearch';
import FoodCard from '@/components/ui/FoodCard';
import FoodConfirm from '@/components/ui/FoodConfirm';
import React from 'react';

export const metadata = {
    title: "Página de Teste",
    description: "Generated by create next app",
  };

const FoodList = () => {
    return (
        <div className="flex flex-col justify-center items-center mt-20">
            <FormFoodSearch />
            <FoodConfirm />
        </div>
    );
};

export default FoodList;
