import Navbar from "@/components/Navbar";

export const metadata = {
    title: "Página Inicial",
    description: "Generated by create next app",
  };

export default function Index() {
    return (
        <div>
        </div>
    )
}
